version: 2.1
orbs:
  python: circleci/python@3.0.0
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Configure missing package
          command: apt-get update && apt-get install libgl1
      - run:
          name: Run tests
          command: pytest -v 
      - store_test_results:
          path: junit.xml
workflows:
  build-and-test:
    jobs:
      - test-python
